#!/usr/bin/python3
import requests
import telebot
from telebot import types

token = '5460636014:AAErtBOZsphYsv1sVMZZMHlDg-Anvu7WGHk'
bot = telebot.TeleBot(token)
nnn = 'норм'

@bot.message_handler(commands=["start"])
def start(m, res=False):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    button_phone = types.KeyboardButton(text='Отправить свой контакт', request_contact=True)
    markup.add(button_phone)
    bot.send_message(m.chat.id, 'Приветствую тебя, {0.first_name}, я информационный бот. '
                                '\nДля получения информации можете воспользоваться подсказками ниже'
                                '\nЧто бы получить доступ к функционалу, отправьте свой номер.'.format(m.from_user),
                     reply_markup=markup)
    user_id = m.from_user.id
    print(user_id)


@bot.message_handler(content_types=['contact'])
def contact(message):
    if message.contact is not None:
        print(message.contact)
        pol = '+' + message.contact.phone_number
        print(message.contact.user_id)
        m = []
        m.append(message.contact.user_id)
        def contact2():
            for i in m:
                if message.contact.user_id in m:
                    if message.contact.user_id == i:
                        global s1
                        s1 = i
        contact2()
        def contact1():
            d = []
            d.append(pol)
            for i in d:
                if pol in d:
                    if pol == i:
                        global s
                        s = i
        contact1()
        bot.send_message(message.from_user.id, 'Запись контакта прошла успешна')
        markup = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
        item1 = types.KeyboardButton('История поездок')
        item2 = types.KeyboardButton('Ближайший самокат')
        item3 = types.KeyboardButton('Информация')
        item4 = types.KeyboardButton("Поддержка")
        markup.add(item1, item2, item3, item4)
        bot.send_message(message.chat.id, 'Что вас интересует?', reply_markup=markup)


@bot.message_handler(content_types=['text'])
def phone(m, res=False):
    if m.chat.type == 'private':
        if m.text == 'История поездок':
            def history():
                try:
                    phn = {'phone': s}
                    url = 'https://uram.ddns.net/uram_bot/history'
                    req_j = requests.post(url, json=phn)
                    req_data = req_j.json()
                    if m.from_user.id != s1:
                        print('FUCK')
                        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
                        button_phone = types.KeyboardButton(text='Отправить свой контакт', request_contact=True)
                        markup.add(button_phone)
                        bot.send_message(m.chat.id,
                                         "Отправьте контакт повторно, произошли неполадки".format(m.from_user),
                                         reply_markup=markup)
                    else:
                        for req_data['history'][0] in req_data['history']:
                            bot.send_message(m.from_user.id, ('Цена: ' + str(req_data['history'][0]['cost']) +
                                                              '\nНачало: ' + req_data['history'][0]['start_time'].
                                                              replace('Mon', 'Понедельник').replace('Tue',
                                                                                                    'Вторник').
                                                              replace('Wed', 'Среда').replace('Thu', 'Четверг').
                                                              replace('Fri', 'Пятница').replace('Sat', 'Суббота').
                                                              replace('Sun', 'Воскресенье').replace('Jan',
                                                                                                    'Января').
                                                              replace('Feb', 'Февраля').replace('Mar', 'Марта').
                                                              replace('Apr', 'Апреля').replace('May', 'Мая').
                                                              replace('June', 'Июня').replace('July', 'Июля').
                                                              replace('Aug', 'Августа').replace('Sept',
                                                                                                'Сентября').
                                                              replace('Oct', 'Октября').replace('Nov', 'Ноября').
                                                              replace('Dec', 'Декабря') +
                                                              '\nКонец: ' + req_data['history'][0]['end_time'].
                                                              replace('Mon', 'Понедельник').replace('Tue',
                                                                                                    'Вторник').
                                                              replace('Wed', 'Среда').replace('Thu', 'Четверг').
                                                              replace('Fri', 'Пятница').replace('Sat', 'Суббота').
                                                              replace('Sun', 'Воскресенье').replace('Jan',
                                                                                                    'Января').
                                                              replace('Feb', 'Февраля').replace('Mar', 'Марта').
                                                              replace('Apr', 'Апреля').replace('May', 'Мая').
                                                              replace('June', 'Июня').replace('July', 'Июля').
                                                              replace('Aug', 'Августа').replace('Sept',
                                                                                                'Сентября').
                                                              replace('Oct', 'Октября').
                                                              replace('Nov', 'Ноября').replace('Dec', 'Декабря') +
                                                              '\nСтатус поездки: ' + req_data['history'][0][
                                                                  'status'].
                                                              replace('end', 'завершена')))
                except KeyError:
                    bot.send_message(m.from_user.id, 'Что то пошло не так')
                except IndexError:
                    print()
                except UnboundLocalError:
                    print()
                except NameError:
                    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
                    button_phone = types.KeyboardButton(text='Отправить свой контакт', request_contact=True)
                    markup.add(button_phone)
                    bot.send_message(m.chat.id,
                                     "Пожалуйста, отправьте ваш контакт и попытайтесь снова".format(m.from_user),
                                     reply_markup=markup)

            t = history()

        elif m.text == 'Ближайший самокат':
            @bot.message_handler(content_types=["location"])
            def location(message):
                if message.location is not None:
                    print(message.location)
                    print(message.contact)
                    print("latitude: %s; longitude: %s" % (message.location.latitude, message.location.longitude))

                    def greting():
                        try:
                            url = 'https://uram.ddns.net/uram_bot/find'
                            req = {'lat': '18', 'lon': '18'}
                            data = message.location.latitude
                            data2 = message.location.longitude
                            req['lat'] = data
                            req['lon'] = data2
                            req['phone'] = s
                            req_j = requests.post(url, json=req)
                            req_data = req_j.json()
                            a = req_data['lat']
                            b = req_data['lon']
                            print(a, b)
                            global result
                            result = a, b
                            print(result)
                            longitude = result[1]
                            latitude = result[0]
                            def block(message):
                                if message.from_user.id == s1:
                                    print(message.from_user.id)
                                    bot.send_location(message.from_user.id, latitude, longitude)
                                    def klon():
                                        mrka = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
                                        but1 = types.KeyboardButton(text='Забронировать самокат')
                                        mrka.add(but1)
                                        bot.send_message(message.from_user.id, "Хотите забронировать этот самокат?",
                                                         reply_markup=mrka)
                                    klon()
                                elif message.from_user.id != s1:
                                    print('xuy: ', message.from_user.id)
                                    bot.send_location(message.from_user.id, latitude, longitude)
                                    def klon():
                                        mrka = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
                                        but1 = types.KeyboardButton(text='Забронировать самокат')
                                        mrka.add(but1)
                                        bot.send_message(message.from_user.id, "Хотите забронировать этот самокат?",
                                                         reply_markup=mrka)
                                    klon()
                            block(message)
                        except:
                            def long():
                                markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
                                button_phone = types.KeyboardButton(text='Отправить свой контакт', request_contact=True)
                                markup.add(button_phone)
                                bot.send_message(m.chat.id, 'Произошла ошибка, отправьте повторно свой контакт'.format(
                                    m.from_user), reply_markup=markup)

                            long()

                    greting()

            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            button_geo = types.KeyboardButton(text="Отправить свое местоположение", request_location=True)
            item5 = types.KeyboardButton(text='Назад')
            keyboard.add(button_geo, item5)
            bot.send_message(m.chat.id, "Отправьте свое местоположение", reply_markup=keyboard)
        elif m.text == 'Информация':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Оплата')
            item2 = types.KeyboardButton(text='Как поехать')
            item3 = types.KeyboardButton(text='Как закончить')
            item4 = types.KeyboardButton(text='Как найти')
            item5 = types.KeyboardButton(text='Назад')
            keyboard.add(item1, item2, item3, item4, item5)
            bot.send_message(m.chat.id, 'Какая информация вас интересует?', reply_markup=keyboard)
        elif m.text == 'Оплата':
            url = 'https://uram.ddns.net/uram_bot/tariffs'
            how = requests.get(url)
            how_data = how.json()
            bot.send_message(m.chat.id, "Оплатить можно наличкой \nСтоимость начало поездки = "
                             + str(how_data['tariffs'][0]['cost_start']) + " рублей \n1 минута поездки = "
                             + str(how_data['tariffs'][0]['cost_minute']) + ' рублей'
                             + '\nОждиание = ' + str(how_data['tariffs'][0]['cost_pause']) + ' рублей')
        elif m.text == 'Как поехать':
            bot.send_message(m.chat.id, 'Чтобы включить электросамокат, достаточно найти его в приложении.'
                                        'Она расположена на руле рядом с информативным дисплеем.'
                                        '\nКогда самокат включится, нажмите специальный курок на руле'
                                        ' самоката и он поедет. Курок расположен на правой рукоятке.')
        elif m.text == 'Как закончить':
            bot.send_message(m.chat.id, "Нужно оставить самокат и заблокировать его.")
        elif m.text == 'Как найти':
            bot.send_message(m.chat.id, "Найти его можно по карте. Или на парковке.")
        elif m.text == 'Назад':
            markup = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton('История поездок')
            item2 = types.KeyboardButton('Ближайший самокат')
            item3 = types.KeyboardButton('Информация')
            item4 = types.KeyboardButton('Поддержка')
            markup.add(item1, item2, item3, item4)
            bot.send_message(m.chat.id, 'Что вас интересует?', reply_markup=markup)
        elif m.text == 'Забронировать самокат':
            def bron():
                print(result)
                kb = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
                bt1 = types.KeyboardButton(text='10 мин')
                bt2 = types.KeyboardButton(text='30 мин')
                bt3 = types.KeyboardButton(text='1 час')
                item5 = types.KeyboardButton(text='Назад')
                kb.add(bt1, bt2, bt3, item5)
                msg = bot.send_message(m.chat.id,
                                       "Чтобы забронировать самокат, выбери ближайшее возможное время,"
                                       "через сколько вы возьмете самокат, после этого времени бронирование пропадет.",
                                       reply_markup=kb)


                bot.register_next_step_handler(msg, after_text_2)

            def after_text_2(message):
                print('Время, на которое человек забронировал самокат', message.text)
                a = bot.send_message(message.chat.id,'Номер:' )
                bot.register_next_step_handler(a, after_text_3)
                global o
                o = message.text
            def after_text_3(message):
                print('Номер: ', message.text)
                k = message.text
                f = open("uid.txt", 'a')
                f.write(str(result) + " " + "на" + " " + str(o) + ', номер бронировщика: ' + k + '\n')
                f.close()
            bron()
        elif m.text == "Поддержка":
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Часто задаваемые вопросы.')
            item2 = types.KeyboardButton(text='Соедените меня с оператором!')
            item3 = types.KeyboardButton(text='Назад')
            keyboard.add(item1, item2, item3)
            bot.send_message(m.chat.id, 'Что вас интересует?', reply_markup=keyboard)
        elif m.text == 'Часто задаваемые вопросы.':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Резко сбросился скорость самоката до 5 км/ч, в чем причина?')
            item3 = types.KeyboardButton(text='Резко сбросился скорость самоката до 10 км/ч, в чем причина?')
            item4 = types.KeyboardButton(text='Как переключаться между режимами на самокате?')
            item5 = types.KeyboardButton(text='Какая масса допускается для езды на самокате?')
            item6 = types.KeyboardButton(text='Какая максимальная скорость у самоката?')
            item2 = types.KeyboardButton(text='Я нажимаю на газ, а самокат не едет, почему?')
            item8 = types.KeyboardButton(text='Назад')
            keyboard.add(item1, item2, item3, item4, item5, item6, item8)
            bot.send_message(m.chat.id, 'Часто задаваемые вопросы.', reply_markup=keyboard)
        elif m.text == 'Резко сбросился скорость самоката до 5 км/ч, в чем причина?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая) {0.first_name}, вы выехали на запрещенную зону где езда на самокате запрещена!'.format(m.from_user))
        elif m.text == 'Резко сбросился скорость самоката до 10 км/ч, в чем причина?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая) {0.first_name}, вы выехали на ограниченную зону где езда на самокате ограничена определенной скоростью для вашей безопасности и окружающих!'.format(m.from_user))
        elif m.text == 'Как переключаться между режимами на самокате?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая) {0.first_name}, что бы переключять режимы на самокате достаточно нажать 2 раза на кнопку "фонарик"'.format(m.from_user))
        elif m.text == 'Какая масса допускается для езды на самокате?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая) {0.first_name}, разрешается езда на самокате до 100 кг!'.format(m.from_user))
        elif m.text == 'Какая максимальная скорость у самоката?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая) {0.first_name}, самоката набирает скорость до 25 км/ч'.format(m.from_user))
        elif m.text == 'Я нажимаю на газ, а самокат не едет, почему?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item1 = types.KeyboardButton(text='Назад')
            keyboard.add(item1)
            bot.send_message(m.chat.id, 'Уважаемый(ая), {0.first_name}, скорее всего вы просто стоите на месте. Для того что бы самокат поехал необходимо оттолкнуться, после чего нажать на газ. Самокат поедет!'.format(m.from_user))
        elif m.text == 'Соедените меня с оператором!':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item2 = types.KeyboardButton(text='Назад')
            item1 = types.KeyboardButton(text='Как будет вам легче соединиться с оператором?')
            keyboard.add(item1, item2)
            bot.send_message(m.chat.id, 'Как будет вам легче соединиться с оператором?', reply_markup=keyboard)
        elif m.text == 'Как будет вам легче соединиться с оператором?':
            keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
            item4 = types.KeyboardButton(text='Назад')
            item1 = types.KeyboardButton(text='Номер телефона')
            item3 = types.KeyboardButton(text='Почтовый адрес')
            item2 = types.KeyboardButton(text='Никнейм разработчика в телеграмме')
            keyboard.add(item1, item2, item3, item4)
            bot.send_message(m.chat.id, 'Соедените меня с оператором!', reply_markup=keyboard)
        elif m.text == 'Никнейм разработчика в телеграмме':
            nik = ["@fa_airat ::: @Odriskoll ::: @happy_rustik"]
            bot.send_message(m.chat.id, nik)
        elif m.text == 'Номер телефона':
            number = [" @fa_airat - 89174009767\n"
                      "@Odriskoll - 89178056873\n"
                      "@happy_rustik - 89273586384"]
            bot.send_message(m.chat.id, number)
        elif m.text == 'Почтовый адрес':
            poshta = [" @fa_airat - airat1956@mail.ru\n"
                      "@Odriskoll - nikolenas0606@imbox.ru\n"
                      "@happy_rustik - rustam.sadykov.777@yandex.ru"]
            bot.send_message(m.chat.id, poshta)


print('bot started')
bot.infinity_polling()
